ALTER TABLE "Product" ADD COLUMN "variants" JSONB NOT NULL DEFAULT '[]'::JSONB;

ALTER TABLE "OrderItem" ADD COLUMN "variantSku" TEXT NOT NULL DEFAULT '';
ALTER TABLE "OrderItem" ADD COLUMN "selectedColor" TEXT NOT NULL DEFAULT '';
ALTER TABLE "OrderItem" ADD COLUMN "selectedSize" TEXT NOT NULL DEFAULT '';
